### ISSUE TITLE
Do I have to charge to package Android?

### ISSUE THREAD

**Issue by wizVR-zhangjun** [zappar-xr/unity-example-face-tracking-face-mesh#1]
It only takes about 30 seconds to package to Android

**Comment by nfynt-zap** [comment]
Any unregistered build has 30sec of trial duration. You will need a free hobbyist license for unlimited personal use or premium ones for production. Please refer to our documents page [here](https://docs.zap.works/universal-ar/general/licensing/) for more details on licensing and registering your product.
