### ISSUE TITLE
Webcam doesn’t start in the build .exe

### ISSUE THREAD

**Issue by cri30** [zappar-xr/unity-example-face-tracking-face-mesh#2]
Hi,

I have tested out the Package and it seems to work on the editor, but not in the build .exe. One of the main issues is related to the webcam that doesn’t start. 

Any idea?

**Comment by nfynt-zap** [comment]
Hi, we don't support any Standalone platform as build target. With UAR we only support build target for - Android, iOS, or WebGL; and In-Editor testing on Win and Mac.
